# LDMS AUTH CLIENT NOTEBOOK
1. ## Setup and installation
2. ## Credentials upload
3. ## List available metrics
4. ## Example of fetching data 
   1. ### Retrieving Complete Data (estimate_number_samples_without_fetching_data=False)
   2. ### Estimating Sample Count Without Data Retrieval
   3. ### Downsampling option (raw (None),min,max,median,std)
   4. ### With Pagination
5. ## Example of fetching power metrics
   1. ### Retrieving Complete Data (estimate_number_samples_without_fetching_data=False)
   2. ### Estimating Sample Count Without Data Retrieval
   3. ### Downsampling option (raw (None),min,max,median,std)
   4. ### With Pagination
6. ## Example of using generic method (to fetch metrics not grouped by job - open to staff only)
   - Example of using generic method (to fetch metrics not grouped by job - open to staff only): With downsampling optio
8. ## Example of fetching job metadata

# LDMS Auth Client Notebook
## 1. Setup and Installation

In [1]:
import pandas as pd

## 2. Credential Upload ( Make Sure to upload the clientid.txt and priv_key.jwk token files to the current directory, which you downloaded from Iris SF API client) 
## Authentication and Session Setup
### **ensure that the client_id and private_key variables in "iris_sfapi_client_credentials" are populated with values received from the SF API token from Iris**

In [2]:
import API_interface as ldms
from iris_sfapi_client_credentials import client_id,private_key
session=ldms.get_session(client_id,private_key)
session.fetch_token()

{'access_token': 'eyJraWQiOiJST3AzIiwidHlwIjoiYXQrand0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ3czN4ZTJ4d2JiMmhxIiwic2NwIjpbImNvbG9yOmdyZWVuIiwiaHR0cHM6Ly9hcGkubmVyc2MuZ292IiwiaXA6MTMxLjI0My4xNDguMjMzXzEyOC41NS4yMDYuMC8yNF8xMjguNTUuMjA1LjAvMjRfMTI4LjU1LjY0LjAvMTgiLCJ1bjpkaHJ1dmEiXSwiaXNzIjoiaHR0cHM6Ly9vaWRjLm5lcnNjLmdvdi9jMmlkIiwiZXhwIjoxNzY3ODMxNDI2LCJpYXQiOjE3Njc4MzA4MjYsImp0aSI6IkNLaU9DY0p5X1FFIiwiY2lkIjoid3MzeGUyeHdiYjJocSJ9.YaP3CruiJ1wju_E4r8PMcIB0cFfzLsA9x0l1eVFLukK_1J5Q9u-AE8u-p3XYksjsIcD97XJodyvLhkVhtbrlMcuHfbjzl7zgBSFIVk8sVMRmEHgf0X3qnRfiOFKS0QAeFS6KzfapKdTVCeJD_r1B3TYbvhCIMB6yomhc6qZM8u99zXK1vXl_RTo_7u6e8pb1ElyO3XYKQjh6qE9KUakTEWna2qbJNdKH0yu004OV4Pb3H_TgTM8rDZTDFaO_3G90TNoivAjUiiIULVk5aOvYW-L0BgSgiEZPZ7Pb8sd5F8F0I5iruLL4cJg6ZYutaMTxrexR2Qck8A8ywm--nm1mzg',
 'scope': 'color:green https://api.nersc.gov ip:131.243.148.233_128.55.206.0/24_128.55.205.0/24_128.55.64.0/18 un:dhruva',
 'token_type': 'Bearer',
 'expires_in': 600,
 'expires_at': 1767831426}

## 3. List Available Metrics 
- Get List of Metrics supported via API

In [3]:
ldms.get_metric_list(session)

{'metrics': ['nersc_ldms_dcgm_board_limit_violation',
  'nersc_ldms_dcgm_correctable_remapped_rows',
  'nersc_ldms_dcgm_dec_utilization',
  'nersc_ldms_dcgm_dram_active',
  'nersc_ldms_dcgm_ecc',
  'nersc_ldms_dcgm_ecc_dbe_aggregate_total',
  'nersc_ldms_dcgm_ecc_dbe_volatile_total',
  'nersc_ldms_dcgm_ecc_sbe_aggregate_total',
  'nersc_ldms_dcgm_ecc_sbe_volatile_l1',
  'nersc_ldms_dcgm_ecc_sbe_volatile_total',
  'nersc_ldms_dcgm_enc_utilization',
  'nersc_ldms_dcgm_fb_free',
  'nersc_ldms_dcgm_fb_used',
  'nersc_ldms_dcgm_fp16_active',
  'nersc_ldms_dcgm_fp32_active',
  'nersc_ldms_dcgm_fp64_active',
  'nersc_ldms_dcgm_gpu_temp',
  'nersc_ldms_dcgm_gpu_utilization',
  'nersc_ldms_dcgm_gr_engine_active',
  'nersc_ldms_dcgm_low_util_violation',
  'nersc_ldms_dcgm_mem_copy_utilization',
  'nersc_ldms_dcgm_memory_clock',
  'nersc_ldms_dcgm_memory_temp',
  'nersc_ldms_dcgm_nvlink_bandwidth_total',
  'nersc_ldms_dcgm_nvlink_data_crc_error_count_total',
  'nersc_ldms_dcgm_nvlink_flit_crc_error_count_l0',
  'nersc_ldms_dcgm_nvlink_flit_crc_error_count_l1',
  'nersc_ldms_dcgm_nvlink_flit_crc_error_count_l2',
  'nersc_ldms_dcgm_nvlink_flit_crc_error_count_l3',
  'nersc_ldms_dcgm_nvlink_flit_crc_error_count_total',
  'nersc_ldms_dcgm_nvlink_recovery_error_count_total',
  'nersc_ldms_dcgm_nvlink_replay_error_count_total',
  'nersc_ldms_dcgm_nvlink_rx_bytes',
  'nersc_ldms_dcgm_nvlink_tx_bytes',
  'nersc_ldms_dcgm_pcie_link_gen',
  'nersc_ldms_dcgm_pcie_link_width',
  'nersc_ldms_dcgm_pcie_max_link_gen',
  'nersc_ldms_dcgm_pcie_max_link_width',
  'nersc_ldms_dcgm_pcie_replay_counter',
  'nersc_ldms_dcgm_pcie_rx_bytes',
  'nersc_ldms_dcgm_pcie_rx_throughput',
  'nersc_ldms_dcgm_pcie_tx_bytes',
  'nersc_ldms_dcgm_pcie_tx_throughput',
  'nersc_ldms_dcgm_power_usage',
  'nersc_ldms_dcgm_power_violation',
  'nersc_ldms_dcgm_reliability_violation',
  'nersc_ldms_dcgm_retired_pages_dbe',
  'nersc_ldms_dcgm_retired_pages_pending',
  'nersc_ldms_dcgm_retired_pages_sbe',
  'nersc_ldms_dcgm_row_remap_failure',
  'nersc_ldms_dcgm_shutdown_temp',
  'nersc_ldms_dcgm_slowdown_temp',
  'nersc_ldms_dcgm_sm_active',
  'nersc_ldms_dcgm_sm_clock',
  'nersc_ldms_dcgm_sm_occupancy',
  'nersc_ldms_dcgm_sync_boost_violation',
  'nersc_ldms_dcgm_tensor_active',
  'nersc_ldms_dcgm_tensor_hmma_active',
  'nersc_ldms_dcgm_tensor_imma_active',
  'nersc_ldms_dcgm_thermal_violation',
  'nersc_ldms_dcgm_total_energy_consumption',
  'nersc_ldms_dcgm_uncorrectable_remapped_rows',
  'nersc_ldms_dcgm_vgpu_instance_license_status',
  'nersc_ldms_dcgm_xid_errors',
  'nersc_ldms_meminfo_Active',
  'nersc_ldms_meminfo_AnonHugePages',
  'nersc_ldms_meminfo_AnonPages',
  'nersc_ldms_meminfo_Bounce',
  'nersc_ldms_meminfo_Buffers',
  'nersc_ldms_meminfo_Cached',
  'nersc_ldms_meminfo_CmaFree',
  'nersc_ldms_meminfo_CmaTotal',
  'nersc_ldms_meminfo_CommitLimit',
  'nersc_ldms_meminfo_Committed_AS',
  'nersc_ldms_meminfo_DirectMap1G',
  'nersc_ldms_meminfo_DirectMap2M',
  'nersc_ldms_meminfo_DirectMap4k',
  'nersc_ldms_meminfo_Dirty',
  'nersc_ldms_meminfo_FileHugePages',
  'nersc_ldms_meminfo_FilePmdMapped',
  'nersc_ldms_meminfo_HardwareCorrupted',
  'nersc_ldms_meminfo_HugePages_Free',
  'nersc_ldms_meminfo_HugePages_Rsvd',
  'nersc_ldms_meminfo_HugePages_Surp',
  'nersc_ldms_meminfo_HugePages_Total',
  'nersc_ldms_meminfo_Hugepagesize',
  'nersc_ldms_meminfo_Hugetlb',
  'nersc_ldms_meminfo_Inactive',
  'nersc_ldms_meminfo_KReclaimable',
  'nersc_ldms_meminfo_KernelStack',
  'nersc_ldms_meminfo_Mapped',
  'nersc_ldms_meminfo_MemAvailable',
  'nersc_ldms_meminfo_MemFree',
  'nersc_ldms_meminfo_MemTotal',
  'nersc_ldms_meminfo_Mlocked',
  'nersc_ldms_meminfo_NFS_Unstable',
  'nersc_ldms_meminfo_PageTables',
  'nersc_ldms_meminfo_Percpu',
  'nersc_ldms_meminfo_SReclaimable',
  'nersc_ldms_meminfo_SUnreclaim',
  'nersc_ldms_meminfo_Shmem',
  'nersc_ldms_meminfo_ShmemHugePages',
  'nersc_ldms_meminfo_ShmemPmdMapped',
  'nersc_ldms_meminfo_Slab',
  'nersc_ldms_meminfo_SwapCached',
  'nersc_ldms_meminfo_SwapFree',
  'nersc_ldms_meminfo_SwapTotal',
  'nersc_ldms_meminfo_Unevictable',
  'nersc_ldms_meminfo_VmallocChunk',
  'nersc_ldms_meminfo_VmallocTotal',
  'nersc_ldms_meminfo_VmallocUsed',
  'nersc_ldms_meminfo_Writeback',
  'nersc_ldms_meminfo_WritebackTmp',
  'nersc_ldms_procstat_btime',
  'nersc_ldms_procstat_ctxt',
  'nersc_ldms_procstat_guest',
  'nersc_ldms_procstat_guest_nice',
  'nersc_ldms_procstat_idle',
  'nersc_ldms_procstat_iowait',
  'nersc_ldms_procstat_irq',
  'nersc_ldms_procstat_nice',
  'nersc_ldms_procstat_processes',
  'nersc_ldms_procstat_procs_blocked',
  'nersc_ldms_procstat_procs_running',
  'nersc_ldms_procstat_softirq',
  'nersc_ldms_procstat_steal',
  'nersc_ldms_procstat_system',
  'nersc_ldms_procstat_user',
  'nersc_ldms_slingshot_metrics_hni_llr_rx_replay_event',
  'nersc_ldms_slingshot_metrics_hni_llr_tx_replay_event',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_0',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_1',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_2',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_3',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_4',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_5',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_6',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_recv_by_tc_7',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_0',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_1',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_2',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_3',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_4',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_5',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_6',
  'nersc_ldms_slingshot_metrics_hni_multicast_pkts_sent_by_tc_7',
  'nersc_ldms_slingshot_metrics_hni_pcs_corrected_cw',
  'nersc_ldms_slingshot_metrics_hni_pcs_good_cw',
  'nersc_ldms_slingshot_metrics_hni_pcs_uncorrected_cw',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_0',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_1',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_2',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_3',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_4',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_5',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_6',
  'nersc_ldms_slingshot_metrics_hni_pkts_recv_by_tc_7',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_0',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_1',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_2',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_3',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_4',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_5',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_6',
  'nersc_ldms_slingshot_metrics_hni_pkts_sent_by_tc_7',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_0',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_1',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_2',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_3',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_4',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_5',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_6',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_7',
  'nersc_ldms_slingshot_metrics_hni_rx_paused_std',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_0',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_1',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_2',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_3',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_4',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_5',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_6',
  'nersc_ldms_slingshot_metrics_hni_tx_paused_7',
  'nersc_ldms_slingshot_metrics_parbs_tarb_pi_non_posted_blocked_cnt',
  'nersc_ldms_slingshot_metrics_parbs_tarb_pi_non_posted_pkts',
  'nersc_ldms_slingshot_metrics_parbs_tarb_pi_posted_blocked_cnt',
  'nersc_ldms_slingshot_metrics_parbs_tarb_pi_posted_pkts',
  'nersc_ldms_slingshot_metrics_pct_sct_timeouts',
  'nersc_ldms_slingshot_metrics_pct_spt_timeouts',
  'nersc_ldms_slingshot_metrics_pct_tct_timeouts',
  'nersc_ldms_slingshot_metrics_pct_trs_replay_pend_drops',
  'nersc_ldms_vmstat_allocstall_dma',
  'nersc_ldms_vmstat_allocstall_dma32',
  'nersc_ldms_vmstat_allocstall_movable',
  'nersc_ldms_vmstat_allocstall_normal',
  'nersc_ldms_vmstat_balloon_deflate',
  'nersc_ldms_vmstat_balloon_inflate',
  'nersc_ldms_vmstat_balloon_migrate',
  'nersc_ldms_vmstat_cma_alloc_fail',
  'nersc_ldms_vmstat_cma_alloc_success',
  'nersc_ldms_vmstat_compact_daemon_free_scanned',
  'nersc_ldms_vmstat_compact_daemon_migrate_scanned',
  'nersc_ldms_vmstat_compact_daemon_wake',
  'nersc_ldms_vmstat_compact_fail',
  'nersc_ldms_vmstat_compact_free_scanned',
  'nersc_ldms_vmstat_compact_isolated',
  'nersc_ldms_vmstat_compact_migrate_scanned',
  'nersc_ldms_vmstat_compact_stall',
  'nersc_ldms_vmstat_compact_success',
  'nersc_ldms_vmstat_direct_map_level2_splits',
  'nersc_ldms_vmstat_direct_map_level3_splits',
  'nersc_ldms_vmstat_drop_pagecache',
  'nersc_ldms_vmstat_drop_slab',
  'nersc_ldms_vmstat_htlb_buddy_alloc_fail',
  'nersc_ldms_vmstat_htlb_buddy_alloc_success',
  'nersc_ldms_vmstat_kswapd_high_wmark_hit_quickly',
  'nersc_ldms_vmstat_kswapd_inodesteal',
  'nersc_ldms_vmstat_kswapd_low_wmark_hit_quickly',
  'nersc_ldms_vmstat_nr_active_anon',
  'nersc_ldms_vmstat_nr_active_file',
  'nersc_ldms_vmstat_nr_anon_pages',
  'nersc_ldms_vmstat_nr_anon_transparent_hugepages',
  'nersc_ldms_vmstat_nr_bounce',
  'nersc_ldms_vmstat_nr_dirtied',
  'nersc_ldms_vmstat_nr_dirty',
  'nersc_ldms_vmstat_nr_dirty_background_threshold',
  'nersc_ldms_vmstat_nr_dirty_threshold',
  'nersc_ldms_vmstat_nr_file_hugepages',
  'nersc_ldms_vmstat_nr_file_pages',
  'nersc_ldms_vmstat_nr_file_pmdmapped',
  'nersc_ldms_vmstat_nr_foll_pin_acquired',
  'nersc_ldms_vmstat_nr_foll_pin_released',
  'nersc_ldms_vmstat_nr_free_cma',
  'nersc_ldms_vmstat_nr_free_pages',
  'nersc_ldms_vmstat_nr_inactive_anon',
  'nersc_ldms_vmstat_nr_inactive_file',
  'nersc_ldms_vmstat_nr_isolated_anon',
  'nersc_ldms_vmstat_nr_isolated_file',
  'nersc_ldms_vmstat_nr_kernel_misc_reclaimable',
  'nersc_ldms_vmstat_nr_kernel_stack',
  'nersc_ldms_vmstat_nr_mapped',
  'nersc_ldms_vmstat_nr_mlock',
  'nersc_ldms_vmstat_nr_page_table_pages',
  'nersc_ldms_vmstat_nr_shmem',
  'nersc_ldms_vmstat_nr_shmem_hugepages',
  'nersc_ldms_vmstat_nr_shmem_pmdmapped',
  'nersc_ldms_vmstat_nr_slab_reclaimable',
  'nersc_ldms_vmstat_nr_slab_unreclaimable',
  'nersc_ldms_vmstat_nr_swapcached',
  'nersc_ldms_vmstat_nr_throttled_written',
  'nersc_ldms_vmstat_nr_unaccepted',
  'nersc_ldms_vmstat_nr_unevictable',
  'nersc_ldms_vmstat_nr_unstable',
  'nersc_ldms_vmstat_nr_vmscan_immediate_reclaim',
  'nersc_ldms_vmstat_nr_vmscan_write',
  'nersc_ldms_vmstat_nr_writeback',
  'nersc_ldms_vmstat_nr_writeback_temp',
  'nersc_ldms_vmstat_nr_written',
  'nersc_ldms_vmstat_nr_zone_active_anon',
  'nersc_ldms_vmstat_nr_zone_active_file',
  'nersc_ldms_vmstat_nr_zone_inactive_anon',
  'nersc_ldms_vmstat_nr_zone_inactive_file',
  'nersc_ldms_vmstat_nr_zone_unevictable',
  'nersc_ldms_vmstat_nr_zone_write_pending',
  'nersc_ldms_vmstat_nr_zspages',
  'nersc_ldms_vmstat_numa_foreign',
  'nersc_ldms_vmstat_numa_hint_faults',
  'nersc_ldms_vmstat_numa_hint_faults_local',
  'nersc_ldms_vmstat_numa_hit',
  'nersc_ldms_vmstat_numa_huge_pte_updates',
  'nersc_ldms_vmstat_numa_interleave',
  'nersc_ldms_vmstat_numa_local',
  'nersc_ldms_vmstat_numa_miss',
  'nersc_ldms_vmstat_numa_other',
  'nersc_ldms_vmstat_numa_pages_migrated',
  'nersc_ldms_vmstat_numa_pte_updates',
  'nersc_ldms_vmstat_oom_kill',
  'nersc_ldms_vmstat_pageoutrun',
  'nersc_ldms_vmstat_pgactivate',
  'nersc_ldms_vmstat_pgalloc_dma',
  'nersc_ldms_vmstat_pgalloc_dma32',
  'nersc_ldms_vmstat_pgalloc_movable',
  'nersc_ldms_vmstat_pgalloc_normal',
  'nersc_ldms_vmstat_pgdeactivate',
  'nersc_ldms_vmstat_pgdemote_direct',
  'nersc_ldms_vmstat_pgdemote_kswapd',
  'nersc_ldms_vmstat_pgfault',
  'nersc_ldms_vmstat_pgfree',
  'nersc_ldms_vmstat_pginodesteal',
  'nersc_ldms_vmstat_pglazyfree',
  'nersc_ldms_vmstat_pglazyfreed',
  'nersc_ldms_vmstat_pgmajfault',
  'nersc_ldms_vmstat_pgmigrate_fail',
  'nersc_ldms_vmstat_pgmigrate_success',
  'nersc_ldms_vmstat_pgpgin',
  'nersc_ldms_vmstat_pgpgout',
  'nersc_ldms_vmstat_pgpromote_success',
  'nersc_ldms_vmstat_pgrefill',
  'nersc_ldms_vmstat_pgreuse',
  'nersc_ldms_vmstat_pgrotated',
  'nersc_ldms_vmstat_pgscan_anon',
  'nersc_ldms_vmstat_pgscan_direct',
  'nersc_ldms_vmstat_pgscan_direct_throttle',
  'nersc_ldms_vmstat_pgscan_file',
  'nersc_ldms_vmstat_pgscan_kswapd',
  'nersc_ldms_vmstat_pgskip_dma',
  'nersc_ldms_vmstat_pgskip_dma32',
  'nersc_ldms_vmstat_pgskip_movable',
  'nersc_ldms_vmstat_pgskip_normal',
  'nersc_ldms_vmstat_pgsteal_anon',
  'nersc_ldms_vmstat_pgsteal_direct',
  'nersc_ldms_vmstat_pgsteal_file',
  'nersc_ldms_vmstat_pgsteal_kswapd',
  'nersc_ldms_vmstat_pswpin',
  'nersc_ldms_vmstat_pswpout',
  'nersc_ldms_vmstat_slabs_scanned',
  'nersc_ldms_vmstat_swap_ra',
  'nersc_ldms_vmstat_swap_ra_hit',
  'nersc_ldms_vmstat_thp_collapse_alloc',
  'nersc_ldms_vmstat_thp_collapse_alloc_failed',
  'nersc_ldms_vmstat_thp_deferred_split_page',
  'nersc_ldms_vmstat_thp_fault_alloc',
  'nersc_ldms_vmstat_thp_fault_fallback',
  'nersc_ldms_vmstat_thp_fault_fallback_charge',
  'nersc_ldms_vmstat_thp_file_alloc',
  'nersc_ldms_vmstat_thp_file_fallback',
  'nersc_ldms_vmstat_thp_file_fallback_charge',
  'nersc_ldms_vmstat_thp_file_mapped',
  'nersc_ldms_vmstat_thp_migration_fail',
  'nersc_ldms_vmstat_thp_migration_split',
  'nersc_ldms_vmstat_thp_migration_success',
  'nersc_ldms_vmstat_thp_split_page',
  'nersc_ldms_vmstat_thp_split_page_failed',
  'nersc_ldms_vmstat_thp_split_pmd',
  'nersc_ldms_vmstat_thp_split_pud',
  'nersc_ldms_vmstat_thp_swpout',
  'nersc_ldms_vmstat_thp_swpout_fallback',
  'nersc_ldms_vmstat_thp_zero_page_alloc',
  'nersc_ldms_vmstat_thp_zero_page_alloc_failed',
  'nersc_ldms_vmstat_unevictable_pgs_cleared',
  'nersc_ldms_vmstat_unevictable_pgs_culled',
  'nersc_ldms_vmstat_unevictable_pgs_mlocked',
  'nersc_ldms_vmstat_unevictable_pgs_munlocked',
  'nersc_ldms_vmstat_unevictable_pgs_rescued',
  'nersc_ldms_vmstat_unevictable_pgs_scanned',
  'nersc_ldms_vmstat_unevictable_pgs_stranded',
  'nersc_ldms_vmstat_workingset_activate_anon',
  'nersc_ldms_vmstat_workingset_activate_file',
  'nersc_ldms_vmstat_workingset_nodereclaim',
  'nersc_ldms_vmstat_workingset_nodes',
  'nersc_ldms_vmstat_workingset_refault_anon',
  'nersc_ldms_vmstat_workingset_refault_file',
  'nersc_ldms_vmstat_workingset_restore_anon',
  'nersc_ldms_vmstat_workingset_restore_file',
  'nersc_ldms_vmstat_zone_reclaim_failed']}

# 4.A Example of Fetching Data: Retrieving Complete Data (estimate_number_samples_without_fetching_data=False)
- Currently, DCGM is fully supported, and other samplers are partially supported.
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example: userid='sp21', jobid='32038251', machine_id='perlmutter gpu'

### Specify list of metrics
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Options: user_defined_slices: TBImplemented


### Result: pandas dataframe with required data

In [5]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sclassen'
jobid='46890374'
machine_id='perlmutter gpu'
metric_list=['nersc_ldms_dcgm_enc_utilization','nersc_ldms_dcgm_fb_free','nersc_ldms_dcgm_fb_used']

estimate_number_samples_without_fetching_data=False
aggr_func="raw"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

print(f'Inputs: userid:{userid},jobid:{jobid},metric_list:{metric_list}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_metrics(session,
                userid ,jobid,machine_id,metric_list,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id}")
    df_mem,num_rows=ldms.get_dataframe(session, task_id, offset=0, size=0, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem

Inputs: userid:sclassen,jobid:46890374,metric_list:['nersc_ldms_dcgm_enc_utilization', 'nersc_ldms_dcgm_fb_free', 'nersc_ldms_dcgm_fb_used']
Options: estimate_size_only:False,aggr_func:raw,timewindow:15,timewindow_unit:s
Sending Request
Task 6ea1aa81-e70c-4d20-961d-c996baf83f61 registered with server
Polling for result on 6ea1aa81-e70c-4d20-961d-c996baf83f61
PENDING

,index,timestamp,hostname,gpu_id,nersc_ldms_dcgm_enc_utilization,nersc_ldms_dcgm_fb_free,nersc_ldms_dcgm_fb_used
0,0,2025-12-23 19:40:20.555,nid003096,3,0,40326,0
1,1,2025-12-23 19:40:20.556,nid003096,1,0,40326,0
2,2,2025-12-23 19:40:20.556,nid003096,2,0,40326,0
3,3,2025-12-23 19:40:20.557,nid003096,0,0,40326,0
4,4,2025-12-23 19:40:30.552,nid003096,1,0,40326,0
5,5,2025-12-23 19:40:30.552,nid003096,2,0,40326,0
6,6,2025-12-23 19:40:30.552,nid003096,3,0,40326,0
7,7,2025-12-23 19:40:30.553,nid003096,0,0,40326,0
8,8,2025-12-23 19:40:40.556,nid003096,3,0,40326,0
9,9,2025-12-23 19:40:40.557,nid003096,0,0,40326,0
10,10,2025-12-23 19:40:40.557,nid003096,1,0,40326,0
11,11,2025-12-23 19:40:40.557,nid003096,2,0,40326,0
12,12,2025-12-23 19:40:50.545,nid003096,3,0,40326,0
13,13,2025-12-23 19:40:50.546,nid003096,0,0,40326,0
14,14,2025-12-23 19:40:50.546,nid003096,1,0,40326,0
15,15,2025-12-23 19:40:50.546,nid003096,2,0,40326,0
16,16,2025-12-23 19:41:00.553,nid003096,1,0,40326,0
17,17,2025-12-23 19:41:00.553,nid003096,2,0,40326,0
18,18,2025-12-23 19:41:00.553,nid003096,3,0,40326,0
19,19,2025-12-23 19:41:00.554,nid003096,0,0,40326,0
20,20,2025-12-23 19:41:10.559,nid003096,2,0,40326,0
21,21,2025-12-23 19:41:10.559,nid003096,3,0,40326,0
22,22,2025-12-23 19:41:10.560,nid003096,0,0,40326,0
23,23,2025-12-23 19:41:10.560,nid003096,1,0,40326,0
24,24,2025-12-23 19:41:20.571,nid003096,2,0,40326,0
25,25,2025-12-23 19:41:20.571,nid003096,3,0,40326,0
26,26,2025-12-23 19:41:20.572,nid003096,0,0,40326,0
27,27,2025-12-23 19:41:20.572,nid003096,1,0,40326,0
28,28,2025-12-23 19:41:30.540,nid003096,1,0,40326,0
29,29,2025-12-23 19:41:30.540,nid003096,2,0,40326,0
30,30,2025-12-23 19:41:30.540,nid003096,3,0,40326,0
31,31,2025-12-23 19:41:30.541,nid003096,0,0,40326,0
32,32,2025-12-23 19:41:40.610,nid003096,3,0,40326,0
33,33,2025-12-23 19:41:40.611,nid003096,1,0,40326,0
34,34,2025-12-23 19:41:40.611,nid003096,2,0,40326,0
35,35,2025-12-23 19:41:40.612,nid003096,0,0,40326,0
36,36,2025-12-23 19:41:50.576,nid003096,3,0,40326,0
37,37,2025-12-23 19:41:50.577,nid003096,0,0,40326,0
38,38,2025-12-23 19:41:50.577,nid003096,1,0,40326,0
39,39,2025-12-23 19:41:50.577,nid003096,2,0,40326,0
40,40,2025-12-23 19:42:00.566,nid003096,1,0,40326,0
41,41,2025-12-23 19:42:00.566,nid003096,2,0,40326,0
42,42,2025-12-23 19:42:00.566,nid003096,3,0,40326,0
43,43,2025-12-23 19:42:00.567,nid003096,0,0,40326,0
44,44,2025-12-23 19:42:10.580,nid003096,3,0,40326,0
45,45,2025-12-23 19:42:10.581,nid003096,1,0,40326,0
46,46,2025-12-23 19:42:10.581,nid003096,2,0,40326,0
47,47,2025-12-23 19:42:10.582,nid003096,0,0,40326,0
48,48,2025-12-23 19:42:20.588,nid003096,1,0,40326,0
49,49,2025-12-23 19:42:20.588,nid003096,2,0,40326,0
50,50,2025-12-23 19:42:20.588,nid003096,3,0,40326,0
51,51,2025-12-23 19:42:20.589,nid003096,0,0,40326,0

# 4.B Example of Fetching Data: Estimating Sample Count Without Data Retrieval
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example: userid='sp21', jobid='32038251', machine_id='perlmutter gpu'

### Specify list of metrics
### set the variable estimate_number_samples_without_fetching_data as `True` 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Options: user_defined_slices: TBImplemented


### Result: pandas dataframe with key as  `Number of samples` and value as `total number of samples` eg: {"Number of samples":"112"}

In [7]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sclassen'
jobid='46890374'
machine_id='perlmutter gpu'
metric_list=['nersc_ldms_dcgm_enc_utilization','nersc_ldms_dcgm_fb_free','nersc_ldms_dcgm_fb_used']

estimate_number_samples_without_fetching_data=True
aggr_func="raw"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

print(f'Inputs: userid:{userid},jobid:{jobid},metric_list:{metric_list}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_metrics(session,
                userid ,jobid,machine_id,metric_list,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id}")
    df_mem=ldms.get_result(session, task_id, offset=0, size=0, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sclassen,jobid:46890374,metric_list:['nersc_ldms_dcgm_enc_utilization', 'nersc_ldms_dcgm_fb_free', 'nersc_ldms_dcgm_fb_used']
Options: estimate_size_only:True,aggr_func:raw,timewindow:15,timewindow_unit:s
Sending Request
Task f42fcf66-4f4d-4593-9628-ccd5290cac0e registered with server
Polling for result on f42fcf66-4f4d-4593-9628-ccd5290cac0e
PENDING

'{"Number of samples": "156"}'

# 4.C Examples of Fetching Data: With Dowmsampling 
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example:
```
 userid='sp21'
 jobid='32038251'
 machine_id='perlmutter gpu'
```

### Specify list of metrics
### set the variable estimate_number_samples_without_fetching_data as `False` 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Examples: 
```
aggr_func="median" # "raw" for (None) or "median" or "std" or "min" or "max"
```
### Options: user_defined_slices: TBImplemented
### Pagination Options: offset, size
- offset specifies the starting point
- size specifies how many results to include
### Example:
```
offset=0
size=0 #( when both offset and size are zero we will be retrieving all the details)
```
### Result: pandas dataframe with a length of 10 starting from the initial point 1.

In [8]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sclassen'
jobid='46890374'
machine_id='perlmutter gpu'
metric_list=['nersc_ldms_dcgm_enc_utilization','nersc_ldms_dcgm_fb_free','nersc_ldms_dcgm_fb_used']

estimate_number_samples_without_fetching_data=False
aggr_func="median"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

#pagination options
offset=0
size=0

print(f'Inputs: userid:{userid},jobid:{jobid},metric_list:{metric_list}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_metrics(session,
                userid ,jobid,machine_id,metric_list,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id} and offset {offset}, size {size}")
    df_mem=ldms.get_result(session, task_id, offset=offset, size=size, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sclassen,jobid:46890374,metric_list:['nersc_ldms_dcgm_enc_utilization', 'nersc_ldms_dcgm_fb_free', 'nersc_ldms_dcgm_fb_used']
Options: estimate_size_only:False,aggr_func:median,timewindow:15,timewindow_unit:s
Sending Request
Task 983ba77a-38ec-4f14-8aaa-1b07187aa696 registered with server
Polling for result on 983ba77a-38ec-4f14-8aaa-1b07187aa696 and offset 0, size 0
PENDING

,index,timestamp,hostname,gpu_id,nersc_ldms_dcgm_enc_utilization,nersc_ldms_dcgm_fb_free,nersc_ldms_dcgm_fb_used
0,0,2025-12-23 19:40:30,nid003096,0,0,40326,0
1,1,2025-12-23 19:40:30,nid003096,1,0,40326,0
2,2,2025-12-23 19:40:30,nid003096,2,0,40326,0
3,3,2025-12-23 19:40:30,nid003096,3,0,40326,0
4,4,2025-12-23 19:40:45,nid003096,0,0,40326,0
5,5,2025-12-23 19:40:45,nid003096,1,0,40326,0
6,6,2025-12-23 19:40:45,nid003096,2,0,40326,0
7,7,2025-12-23 19:40:45,nid003096,3,0,40326,0
8,8,2025-12-23 19:41:00,nid003096,0,0,40326,0
9,9,2025-12-23 19:41:00,nid003096,1,0,40326,0
10,10,2025-12-23 19:41:00,nid003096,2,0,40326,0
11,11,2025-12-23 19:41:00,nid003096,3,0,40326,0
12,12,2025-12-23 19:41:15,nid003096,0,0,40326,0
13,13,2025-12-23 19:41:15,nid003096,1,0,40326,0
14,14,2025-12-23 19:41:15,nid003096,2,0,40326,0
15,15,2025-12-23 19:41:15,nid003096,3,0,40326,0
16,16,2025-12-23 19:41:30,nid003096,0,0,40326,0
17,17,2025-12-23 19:41:30,nid003096,1,0,40326,0
18,18,2025-12-23 19:41:30,nid003096,2,0,40326,0
19,19,2025-12-23 19:41:30,nid003096,3,0,40326,0
20,20,2025-12-23 19:41:45,nid003096,0,0,40326,0
21,21,2025-12-23 19:41:45,nid003096,1,0,40326,0
22,22,2025-12-23 19:41:45,nid003096,2,0,40326,0
23,23,2025-12-23 19:41:45,nid003096,3,0,40326,0
24,24,2025-12-23 19:42:00,nid003096,0,0,40326,0
25,25,2025-12-23 19:42:00,nid003096,1,0,40326,0
26,26,2025-12-23 19:42:00,nid003096,2,0,40326,0
27,27,2025-12-23 19:42:00,nid003096,3,0,40326,0
28,28,2025-12-23 19:42:15,nid003096,0,0,40326,0
29,29,2025-12-23 19:42:15,nid003096,1,0,40326,0
30,30,2025-12-23 19:42:15,nid003096,2,0,40326,0
31,31,2025-12-23 19:42:15,nid003096,3,0,40326,0

# 4.D Examples of Fetching Data: With Pagination
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example:
```
 userid='sp21'
 jobid='32038251'
 machine_id='perlmutter gpu'
```

### Specify list of metrics
### set the variable estimate_number_samples_without_fetching_data as `False` 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Options: user_defined_slices: TBImplemented
### Pagination Options: offset, size
- offset specifies the starting point
- size specifies how many results to include
### Example: 
```
offset=1
size=10
```
### Result: pandas dataframe with a length of 10 starting from the initial point 1.

In [23]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sp21'
jobid='42753949'
machine_id='perlmutter gpu'
metric_list=['nersc_ldms_dcgm_enc_utilization','nersc_ldms_dcgm_fb_free','nersc_ldms_dcgm_fb_used']

estimate_number_samples_without_fetching_data=False
aggr_func="raw"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

#pagination options
offset=0
size=10

print(f'Inputs: userid:{userid},jobid:{jobid},metric_list:{metric_list}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_metrics(session,
                userid ,jobid,machine_id,metric_list,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id} and offset {offset}, size {size}")
    df_mem=ldms.get_result(session, task_id, offset=offset, size=size, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sp21,jobid:42753949,metric_list:['nersc_ldms_dcgm_enc_utilization', 'nersc_ldms_dcgm_fb_free', 'nersc_ldms_dcgm_fb_used']
Options: estimate_size_only:False,aggr_func:raw,timewindow:15,timewindow_unit:s
Sending Request
Task b9be0880-e230-409b-ae28-02a041a7c4c5 registered with server
Polling for result on b9be0880-e230-409b-ae28-02a041a7c4c5 and offset 0, size 10
PENDING

,index,timestamp,hostname,gpu_id,nersc_ldms_dcgm_enc_utilization,nersc_ldms_dcgm_fb_free,nersc_ldms_dcgm_fb_used
0,0,2025-09-13 00:29:10.232,nid001037,0,0,40326,0
1,1,2025-09-13 00:29:10.232,nid001037,1,0,40326,0
2,2,2025-09-13 00:29:10.232,nid001037,2,0,40326,0
3,3,2025-09-13 00:29:10.232,nid001037,3,0,40326,0
4,4,2025-09-13 00:29:20.230,nid001037,0,0,40326,0
5,5,2025-09-13 00:29:20.230,nid001037,1,0,40326,0
6,6,2025-09-13 00:29:20.230,nid001037,2,0,40326,0
7,7,2025-09-13 00:29:20.230,nid001037,3,0,40326,0
8,8,2025-09-13 00:29:30.227,nid001037,0,0,40326,0
9,9,2025-09-13 00:29:30.227,nid001037,1,0,40326,0

# 5.A Example of fetching power metrics: Retrieving Complete Data (estimate_number_samples_without_fetching_data=False)
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example:
```
 userid='sp21'
 jobid='32038251'
 machine_id='perlmutter gpu'
```

### Specify power metric 'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power' 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Options: user_defined_slices: TBImplemented


### Result: pandas dataframe with required data

In [25]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sp21'
jobid='42753949'
machine_id='perlmutter gpu'
power_metric_name='gpu_power' #'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power'

estimate_number_samples_without_fetching_data=False
aggr_func="raw"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

print(f'Inputs: userid:{userid},jobid:{jobid},power_metric_name:{power_metric_name}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_power_metrics(session,
                userid ,jobid,machine_id,power_metric_name,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id}")
    df_mem=ldms.get_result(session, task_id, offset=0, size=0, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sp21,jobid:42753949,power_metric_name:gpu_power
Options: estimate_size_only:False,aggr_func:raw,timewindow:15,timewindow_unit:s
Sending Request
None
Task af3e546d-2208-4f6b-bd46-c521f5a4188f registered with server
Polling for result on af3e546d-2208-4f6b-bd46-c521f5a4188f
PENDING

     index  gpu_id  gpu_power           timestamp   hostname
0        0       3         56 2025-09-13 00:29:09  nid001037
1        1       3         56 2025-09-13 00:29:11  nid001037
2        2       3         56 2025-09-13 00:29:12  nid001037
3        3       3         56 2025-09-13 00:29:14  nid001037
4        4       3         56 2025-09-13 00:29:16  nid001037
..     ...     ...        ...                 ...        ...
163    163       0        106 2025-09-13 00:30:12  nid001037
164    164       0         65 2025-09-13 00:30:14  nid001037
165    165       0         56 2025-09-13 00:30:15  nid001037
166    166       0         56 2025-09-13 00:30:17  nid001037
167    167       0         55 2025-09-13 00:30:19  nid001037

[168 rows x 5 columns]

# 5.B Example of Fetching Power Metric Data: Estimating Sample Count Without Data Retrieval
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example:
```
 userid='sp21'
 jobid='32038251'
 machine_id='perlmutter gpu'
```
### Specify power metric 'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power' 
### set the variable estimate_number_samples_without_fetching_data as `True` 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Options: user_defined_slices: TBImplemented


### Result: pandas dataframe with key as  `Number of samples` and value as `total number of samples` eg: {"Number of samples":"112"}

In [27]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sp21'
jobid='42753949'
machine_id='perlmutter gpu'
power_metric_name='gpu_power' #'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power'

estimate_number_samples_without_fetching_data=True
aggr_func="raw"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

print(f'Inputs: userid:{userid},jobid:{jobid},power_metric_name:{power_metric_name}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_power_metrics(session,
                userid ,jobid,machine_id,power_metric_name,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id}")
    df_mem=ldms.get_result(session, task_id, offset=0, size=0, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sp21,jobid:42753949,power_metric_name:gpu_power
Options: estimate_size_only:True,aggr_func:raw,timewindow:15,timewindow_unit:s
Sending Request
None
Task 7fe44f07-8df2-4a66-9de0-5d2b5b4a5e4a registered with server
Polling for result on 7fe44f07-8df2-4a66-9de0-5d2b5b4a5e4a
PENDING

'{"Number of samples": "168"}'

# 5.C Example of Fetching Power Metric Data: With Dowmsampling 
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example: userid='sp21', jobid='32038251', machine_id='perlmutter gpu'

### Specify power metric 'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power' 
### set the variable estimate_number_samples_without_fetching_data as `False` 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Examples: aggr_func="median" # "raw" for (None)"median" or "std" or "min" or "max"
### Options: user_defined_slices: TBImplemented
### Pagination Options: offset, size
- offset specifies the starting point
- size specifies how many results to include
### Example: offset=0, size=0 ( when both offset and size are zero we will be retrieving all the details)
### Result: pandas dataframe with key as  `Number of samples` and value as `total number of samples` eg: {"Number of samples":"112"}

In [29]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sp21'
jobid='42753949'
machine_id='perlmutter gpu'
power_metric_name='gpu_power' #'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power'

estimate_number_samples_without_fetching_data=False
aggr_func="median"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

#pagination options
offset=0
size=0

print(f'Inputs: userid:{userid},jobid:{jobid},power_metric_name:{power_metric_name}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_power_metrics(session,
                userid ,jobid,machine_id,power_metric_name,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id}")
    df_mem=ldms.get_result(session, task_id, offset=0, size=0, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sp21,jobid:42753949,power_metric_name:gpu_power
Options: estimate_size_only:False,aggr_func:median,timewindow:15,timewindow_unit:s
Sending Request
None
Task 0337cc00-44d7-4a1b-85dd-b38943127823 registered with server
Polling for result on 0337cc00-44d7-4a1b-85dd-b38943127823
PENDING

    index           timestamp  gpu_power  gpu_id   hostname
0       0 2025-09-13 00:29:24         55       0  nid001037
1       1 2025-09-13 00:29:39         55       0  nid001037
2       2 2025-09-13 00:29:54         55       0  nid001037
3       3 2025-09-13 00:30:09         55       0  nid001037
4       4 2025-09-13 00:29:24         53       1  nid001037
5       5 2025-09-13 00:29:39         53       1  nid001037
6       6 2025-09-13 00:29:54         53       1  nid001037
7       7 2025-09-13 00:30:09         53       1  nid001037
8       8 2025-09-13 00:29:24         60       2  nid001037
9       9 2025-09-13 00:29:39         60       2  nid001037
10     10 2025-09-13 00:29:54         60       2  nid001037
11     11 2025-09-13 00:30:09         60       2  nid001037
12     12 2025-09-13 00:29:24         56       3  nid001037
13     13 2025-09-13 00:29:39         56       3  nid001037
14     14 2025-09-13 00:29:54         56       3  nid001037
15     15 2025-09-13 00:30:09         56       3  nid001037

# 5.D Example of Fetching Power Metric Data: With Pagination 
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: userid, jobid, machine_id
### example: 
```
userid='sp21'
jobid='32038251'
machine_id='perlmutter gpu'
```
### Specify power metric 'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power' 
### set the variable estimate_number_samples_without_fetching_data as `False` 
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)
### Examples: aggr_func="median" # "raw" for (None)"median" or "std" or "min" or "max"
### Options: user_defined_slices: TBImplemented
### Pagination Options: offset, size
- offset specifies the starting point
- size specifies how many results to include
### Example: offset=1, size=10 ( when both offset and size are zero we will be retrieving all the details)
### Result: pandas dataframe with key as  `Number of samples` and value as `total number of samples` eg: {"Number of samples":"112"}

In [30]:
from dataclasses import dataclass,asdict

from dataclasses import dataclass,asdict
from typing import Optional,Union, Annotated, List
from datetime import datetime


userid='sp21'
jobid='42753949'
machine_id='perlmutter gpu'
power_metric_name='gpu_power' #'gpu_power' or 'node_power'or 'memory_power'or 'cpu_power'

estimate_number_samples_without_fetching_data=False
aggr_func="raw"
timewindow=15
timewindow_unit="s"
user_defined_slices=None

#pagination options
offset=1
size=10

print(f'Inputs: userid:{userid},jobid:{jobid},power_metric_name:{power_metric_name}')
print(f'Options: estimate_size_only:{estimate_number_samples_without_fetching_data},aggr_func:{aggr_func},timewindow:{timewindow},timewindow_unit:{timewindow_unit}')
print("Sending Request")
response = ldms.fetch_power_metrics(session,
                userid ,jobid,machine_id,power_metric_name,
                estimate_number_samples_without_fetching_data=estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit,
                user_defined_slices=user_defined_slices
            )

print(f'Task {response.get("task_id")} registered with server')
task_id=response.get("task_id")
if not task_id:
    raise RuntimeError(f"No task_id in response: {response}")
try:
    print(f"Polling for result on {task_id}")
    df_mem=ldms.get_result(session, task_id, offset=0, size=0, retries=30, interval=5)
except ValueError as e:
    print(e)

df_mem.data

Inputs: userid:sp21,jobid:42753949,power_metric_name:gpu_power
Options: estimate_size_only:False,aggr_func:raw,timewindow:15,timewindow_unit:s
Sending Request
None
Task 98b34ce7-ab01-4e92-b876-b5875632370f registered with server
Polling for result on 98b34ce7-ab01-4e92-b876-b5875632370f
PENDING

     index  gpu_id  gpu_power           timestamp   hostname
0        0       3         56 2025-09-13 00:29:09  nid001037
1        1       3         56 2025-09-13 00:29:11  nid001037
2        2       3         56 2025-09-13 00:29:12  nid001037
3        3       3         56 2025-09-13 00:29:14  nid001037
4        4       3         56 2025-09-13 00:29:16  nid001037
..     ...     ...        ...                 ...        ...
163    163       2         60 2025-09-13 00:30:12  nid001037
164    164       2         60 2025-09-13 00:30:14  nid001037
165    165       2         60 2025-09-13 00:30:15  nid001037
166    166       2         60 2025-09-13 00:30:17  nid001037
167    167       2         60 2025-09-13 00:30:19  nid001037

[168 rows x 5 columns]

## 6 A. Example of using generic method (to fetch metrics not grouped by job - open to staff only)
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: nodelist_list, start_time_list,endtime_list, sampler_metrics_list,fmt and cols 
```
sampler_metrics_list=["bytesRead:lustre_stats:sum","bytesWritten:lustre_stats:sum"] 
fmt='__timestamp__:unix_s,__name__,__value__'
cols = ['timestamp','__name__','__value__']
```
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)


### Result: pandas dataframe with required data

In [39]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import time
from datetime import datetime
nodelist_list= [[]]
start_time_list=['2025-09-12T00:00:00.000-08:00']
end_time_list=['2025-09-14T01:00:00.000-08:00']

sampler_metrics_list=["bytesRead:lustre_stats:sum","bytesWritten:lustre_stats:sum"]
fmt='__timestamp__:unix_s,__name__,__value__'
cols = ['timestamp','__name__','__value__']
print(f'nodelist_list={nodelist_list} start_time_list= {start_time_list} end_time_list= {end_time_list}')
print(" Sending request... ")
response = ldms.fetch_generic(session,nodelist_list,start_time_list,end_time_list,sampler_metrics_list,fmt,cols)
print(f'response is {response}')
try:
    print("getting the data frame")
    df_generic,_=ldms.get_dataframe(session,response['task_id'],retries=15, interval=10)
except ValueError as e:
    print(e)

df_generic

nodelist_list=[[]] start_time_list= ['2025-09-12T00:00:00.000-08:00'] end_time_list= ['2025-09-14T01:00:00.000-08:00']
 Sending request...
response is None
getting the data frame

## 6.B Example of using generic method (to fetch metrics not grouped by job - open to staff only) with Downsampling Option
# Example API flow: call, receive task ID, poll on task ID, get result as a pandas dataframe.
# The following snippet implements this example flow. Modify inputs as required.

### Enter: nodelist_list, start_time_list,endtime_list, sampler_metrics_list,fmt and cols 
```
sampler_metrics_list=["bytesRead:lustre_stats:sum","bytesWritten:lustre_stats:sum"] 
fmt='__timestamp__:unix_s,__name__,__value__'
cols = ['timestamp','__name__','__value__']
```
### Enter the details for downsampling by choosing the aggregate function ’min’,’ max, ‘std’, 'median’, and ‘raw’ (used for None or no downsampling)
### Assign `True` or `False` based on which retrieves just the total number of samples and retrieving all the data
### Enter time_window
### Enter the timewindow_unit 
```
s --> Seconds
m --> Minite
h --> Hour
d --> Day
w --> Week
y --> Year
```
### Example:
```
estimate_number_samples_without_fetching_data=False
aggr_func='max'
timewindow=15
timewindow_unit="m"
```
### Options: downsampling: time window, function to use (raw (for None),median,min,max,std)


### Result: pandas dataframe with required data

In [ ]:
nodelist_list= [[]]
start_time_list=['2025-09-01T00:00:00.000-08:00']
end_time_list=['2025-09-01T01:00:00.000-08:00']

sampler_metrics_list=["bytesRead:lustre_stats:sum","bytesWritten:lustre_stats:sum"]
fmt='__timestamp__:unix_s,__name__,__value__'
cols = ['timestamp','__name__','__value__']
estimate_number_samples_without_fetching_data=False
aggr_func='max'
timewindow=15
timewindow_unit="m"
print(f'nodelist_list={nodelist_list} start_time_list= {start_time_list} end_time_list= {end_time_list}')
print(f'estimated number samples without fetching data={estimate_number_samples_without_fetching_data} aggr_func={aggr_func} timewindow={timewindow} timewindow_unit={timewindow}')
print('sending request')
response = ldms.fetch_generic(session,nodelist_list,start_time_list,end_time_list,sampler_metrics_list,fmt,cols,
                estimate_number_samples_without_fetching_data,aggr_func=aggr_func,timewindow=timewindow,timewindow_unit=timewindow_unit)
print(response)
try:
    print('getting the data frame')
    df_generic,_=ldms.get_dataframe(session,response['task_id'],retries=15, interval=10)
except ValueError as e:
    print(e)
#df_generic['Time']=pd.to_datetime(df_generic['timestamp'],unit='s',utc=True)

df_generic

### 7. Fetch Job Metadata
### API Flow: call fetch job meta data api, get the response and print it to get the metadata

In [21]:
# Fetching the Job metadata for the userid, jobid and machine_id
userid='sp21'
jobid='42753949'
machine_id='perlmutter gpu'
metrics_list=['nersc_ldms_dcgm_enc_utilization','nersc_ldms_dcgm_fb_free','nersc_ldms_dcgm_fb_used','nersc_ldms_dcgm_dram_active']
response=ldms.fetch_job_metadata(session,userid,jobid,machine_id)
print(response)

{'task_id': '4023a2b0-dff0-4af3-a41b-2aa09a568112', 'logged_in_user': 'sp21'}